/* eslint-disable react-refresh/only-export-components */
import React, { createContext, useContext, useEffect, useState } from 'react';
import authService from '../services/adminAuthService';
import pushNotificationService from '../services/pushNotificationService';

export const AdminAuthContext = createContext({
  user: null,
  login: async () => ({}),
  logout: async () => {},
  updateProfile: async () => ({}),
  subscribeToNotifications: async () => {},
  unsubscribeFromNotifications: async () => {},
  unsubscribeAllDevices: async () => {},
  getSubscriptions: async () => [],
  isAuthenticated: false,
  isLoading: true,
  isSubscribedToNotifications: false,
});

export const AdminAuthContextProvider = ({ children }) => {
  const [user, setUser] = useState(null);
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [isSubscribedToNotifications, setIsSubscribedToNotifications] = useState(false);

  const updateAuthState = (authData) => {
    setUser(authData.user);
    setIsAuthenticated(authData.isAuthenticated);
    if (!authData.isAuthenticated) {
      setIsSubscribedToNotifications(false);
    }
  };

  // 🔧 Helper function to convert VAPID key
  const urlBase64ToUint8Array = (base64String) => {
    const padding = '='.repeat((4 - base64String.length % 4) % 4);
    const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/');
    const rawData = window.atob(base64);
    return Uint8Array.from([...rawData].map((char) => char.charCodeAt(0)));
  };

  // 🔔 Subscribe to push notifications
  const subscribeToNotifications = async (label) => {
    if (!user?.id) {
      throw new Error('Admin must be logged in to subscribe');
    }

    try {
      // 1. Check if browser supports notifications
      if (!('Notification' in window) || !('serviceWorker' in navigator)) {
        throw new Error('Push notifications not supported in this browser');
      }

      // 2. Request permission
      const permission = await Notification.requestPermission();
      if (permission !== 'granted') {
        throw new Error('Notification permission denied');
      }

      // 3. Wait for service worker to be ready
      const registration = await navigator.serviceWorker.ready;

      // 4. Get VAPID public key from environment
      const publicVapidKey = import.meta.env.VITE_VAPID_PUBLIC_KEY;
      if (!publicVapidKey) {
        throw new Error('VAPID public key not configured');
      }

      // 5. Subscribe to push manager
      const subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: urlBase64ToUint8Array(publicVapidKey),
      });

      // 6. Convert subscription to plain object
      const subscriptionObject = subscription.toJSON();

      // 7. Send subscription to backend using push notification service
      await pushNotificationService.subscribe(
        user.id,
        'ADMIN', // UserType
        {
          id: '', // Will be generated by backend
          userId: user.id,
          type: 'ADMIN',
          endpoint: subscriptionObject.endpoint,
          p256dh: subscriptionObject.keys.p256dh,
          auth: subscriptionObject.keys.auth,
          label: label || `${navigator.userAgent.includes('Mobile') ? 'Mobile' : 'Desktop'} Device`,
          createdAt: new Date().toISOString(),
        },
        label
      );

      setIsSubscribedToNotifications(true);

      console.log('✅ Successfully subscribed to push notifications');
      return { success: true, message: 'Successfully subscribed to notifications' };
    } catch (error) {
      console.error('❌ Error subscribing to notifications:', error);
      throw new Error(error?.message || 'Failed to subscribe to notifications');
    }
  };

  // 🔕 Unsubscribe from push notifications (current device only)
  const unsubscribeFromNotifications = async () => {
    if (!user?.id) {
      throw new Error('Admin must be logged in');
    }

    try {
      // 1. Unsubscribe from push manager
      const registration = await navigator.serviceWorker.ready;
      const subscription = await registration.pushManager.getSubscription();
      
      if (subscription) {
        const endpoint = subscription.endpoint;
        
        // Unsubscribe from browser
        await subscription.unsubscribe();

        // 2. Remove subscription from backend
        await pushNotificationService.unsubscribeDevice(
          user.id,
          'ADMIN',
          endpoint
        );
      }

      setIsSubscribedToNotifications(false);

      console.log('✅ Successfully unsubscribed from push notifications');
      return { success: true, message: 'Successfully unsubscribed from notifications' };
    } catch (error) {
      console.error('❌ Error unsubscribing from notifications:', error);
      throw new Error(error?.message || 'Failed to unsubscribe from notifications');
    }
  };

  // 🔕 Unsubscribe all devices
  const unsubscribeAllDevices = async () => {
    if (!user?.id) {
      throw new Error('Admin must be logged in');
    }

    try {
      // Remove all subscriptions from backend
      await pushNotificationService.unsubscribeAllDevices(
        user.id,
        'ADMIN'
      );

      // Also unsubscribe current device from browser
      const registration = await navigator.serviceWorker.ready;
      const subscription = await registration.pushManager.getSubscription();
      if (subscription) {
        await subscription.unsubscribe();
      }

      setIsSubscribedToNotifications(false);

      console.log('✅ Successfully unsubscribed all devices');
      return { success: true, message: 'Successfully unsubscribed all devices' };
    } catch (error) {
      console.error('❌ Error unsubscribing all devices:', error);
      throw new Error(error?.message || 'Failed to unsubscribe all devices');
    }
  };

  // 📋 Get all subscriptions for current admin
  const getSubscriptions = async () => {
    if (!user?.id) {
      throw new Error('Admin must be logged in');
    }

    try {
      const subscriptions = await pushNotificationService.getSubscriptions(
        user.id,
        'ADMIN'
      );
      return subscriptions;
    } catch (error) {
      console.error('❌ Error fetching subscriptions:', error);
      throw new Error(error?.message || 'Failed to fetch subscriptions');
    }
  };

  // 🔍 Check if current device is subscribed
  const checkSubscriptionStatus = async () => {
    if (!user?.id || !isAuthenticated) return;

    try {
      const registration = await navigator.serviceWorker.ready;
      const subscription = await registration.pushManager.getSubscription();
      
      if (subscription) {
        // Verify with backend
        const subscriptions = await pushNotificationService.getSubscriptions(
          user.id,
          'ADMIN'
        );
        
        const isSubscribed = subscriptions.some(
          (sub) => sub.endpoint === subscription.endpoint
        );
        
        setIsSubscribedToNotifications(isSubscribed);
      } else {
        setIsSubscribedToNotifications(false);
      }
    } catch (error) {
      console.warn('Could not check subscription status:', error);
      setIsSubscribedToNotifications(false);
    }
  };

  const login = async (data) => {
    try {
      console.log(data);
      const response = await authService.login(data);
      updateAuthState({
        user: response,
        isAuthenticated: true,
      });
      return response;
    } catch (error) {
      throw new Error(error?.response?.data?.message || error.message);
    }
  };

  const logout = async () => {
    try {
      const response = await authService.logout();
      updateAuthState({ user: null, isAuthenticated: false });
      return response;
    } catch (error) {
      updateAuthState({ user: null, isAuthenticated: false });
      throw new Error(error.message);
    }
  };

  const updateProfile = async (updates) => {
    try {
      const updatedUser = await authService.updateProfile(updates);
      updateAuthState({
        user: updatedUser,
        isAuthenticated: true,
      });
      return updatedUser;
    } catch (error) {
      throw new Error(error.message);
    }
  };

  const checkAuthStatus = async () => {
    setIsLoading(true);
    try {
      const userProfile = await authService.getProfile();
      if (userProfile) {
        updateAuthState({
          user: userProfile,
          isAuthenticated: true,
        });
      } else {
        updateAuthState({ user: null, isAuthenticated: false });
      }
    } catch {
      updateAuthState({ user: null, isAuthenticated: false });
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    // ✅ Always verify session with backend (cookie is sent automatically)
    checkAuthStatus();
  }, []);

  // 🔍 Check subscription status when authenticated
  useEffect(() => {
    if (isAuthenticated && !isLoading && user?.id) {
      checkSubscriptionStatus();
    }
  }, [isAuthenticated, isLoading, user?.id]);

  // 🔔 Auto-subscribe on login (optional)
  useEffect(() => {
    const autoSubscribe = async () => {
      // Only run if authenticated and not already subscribed
      if (!isAuthenticated || isLoading || !user?.id || isSubscribedToNotifications) {
        return;
      }

      // Check if admin wants auto-subscribe
      const autoSubscribeEnabled = localStorage.getItem('autoSubscribePushAdmin') === 'true';
      
      if (autoSubscribeEnabled) {
        try {
          await subscribeToNotifications('Auto-subscribed device');
        } catch (error) {
          console.warn('Auto-subscribe failed:', error);
        }
      }
    };

    autoSubscribe();
  }, [isAuthenticated, isLoading, user?.id, isSubscribedToNotifications]);

  const values = {
    login,
    logout,
    updateProfile,
    subscribeToNotifications,
    unsubscribeFromNotifications,
    unsubscribeAllDevices,
    getSubscriptions,
    user,
    isLoading,
    isAuthenticated,
    isSubscribedToNotifications,
  };

  return (
    <AdminAuthContext.Provider value={values}>{children}</AdminAuthContext.Provider>
  );
};

export default function useAdminAuth() {
  const context = useContext(AdminAuthContext);
  if (!context) {
    throw new Error('useAdminAuth must be used within AdminAuthContextProvider');
  }
  return context;
}