/* eslint-disable react-refresh/only-export-components */
import React, { createContext, useContext, useEffect, useState } from 'react';
import companyAuthService from '../services/companyAuthService';
import pushNotificationService from '../services/pushNotificationService';

// ✅ Create context
const CompanyAuthContext = createContext({
  company: null,
  login: async () => {},
  register: async () => {},
  logout: async () => {},
  updateProfile: async () => {},
  subscribeToNotifications: async () => {},
  unsubscribeFromNotifications: async () => {},
  unsubscribeAllDevices: async () => {},
  getSubscriptions: async () => [],
  isAuthenticated: false,
  isLoading: true,
  isSubscribedToNotifications: false,
});

// ✅ Provider
export const CompanyAuthProvider = ({ children }) => {
  const [company, setCompany] = useState(null);
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [isSubscribedToNotifications, setIsSubscribedToNotifications] = useState(false);

  const updateAuthState = (userData, authStatus) => {
    setCompany(userData);
    setIsAuthenticated(authStatus);
    if (!authStatus) {
      setIsSubscribedToNotifications(false);
    }
  };

  // 🔧 Helper function to convert VAPID key
  const urlBase64ToUint8Array = (base64String) => {
    const padding = '='.repeat((4 - base64String.length % 4) % 4);
    const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/');
    const rawData = window.atob(base64);
    return Uint8Array.from([...rawData].map((char) => char.charCodeAt(0)));
  };

  // 🔔 Subscribe to push notifications
  const subscribeToNotifications = async (label) => {
    if (!company?.id) {
      throw new Error('Company must be logged in to subscribe');
    }

    try {
      // 1. Check if browser supports notifications
      if (!('Notification' in window) || !('serviceWorker' in navigator)) {
        throw new Error('Push notifications not supported in this browser');
      }

      // 2. Request permission
      const permission = await Notification.requestPermission();
      if (permission !== 'granted') {
        throw new Error('Notification permission denied');
      }

      // 3. Wait for service worker to be ready
      const registration = await navigator.serviceWorker.ready;

      // 4. Get VAPID public key from environment
      const publicVapidKey = import.meta.env.VITE_VAPID_PUBLIC_KEY;
      if (!publicVapidKey) {
        throw new Error('VAPID public key not configured');
      }

      // 5. Subscribe to push manager
      const subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: urlBase64ToUint8Array(publicVapidKey),
      });

      // 6. Convert subscription to plain object
      const subscriptionObject = subscription.toJSON();

      // 7. Send subscription to backend using push notification service
      await pushNotificationService.subscribe(
        company.id,
        'COMPANY', // UserType
        {
          id: '', // Will be generated by backend
          userId: company.id,
          type: 'COMPANY',
          endpoint: subscriptionObject.endpoint,
          p256dh: subscriptionObject.keys.p256dh,
          auth: subscriptionObject.keys.auth,
          label: label || `${navigator.userAgent.includes('Mobile') ? 'Mobile' : 'Desktop'} Device`,
          createdAt: new Date().toISOString(),
        },
        label
      );

      setIsSubscribedToNotifications(true);

      console.log('✅ Successfully subscribed to push notifications');
      return { success: true, message: 'Successfully subscribed to notifications' };
    } catch (error) {
      console.error('❌ Error subscribing to notifications:', error);
      throw new Error(error?.message || 'Failed to subscribe to notifications');
    }
  };

  // 🔕 Unsubscribe from push notifications (current device only)
  const unsubscribeFromNotifications = async () => {
    if (!company?.id) {
      throw new Error('Company must be logged in');
    }

    try {
      // 1. Unsubscribe from push manager
      const registration = await navigator.serviceWorker.ready;
      const subscription = await registration.pushManager.getSubscription();
      
      if (subscription) {
        const endpoint = subscription.endpoint;
        
        // Unsubscribe from browser
        await subscription.unsubscribe();

        // 2. Remove subscription from backend
        await pushNotificationService.unsubscribeDevice(
          company.id,
          'COMPANY',
          endpoint
        );
      }

      setIsSubscribedToNotifications(false);

      console.log('✅ Successfully unsubscribed from push notifications');
      return { success: true, message: 'Successfully unsubscribed from notifications' };
    } catch (error) {
      console.error('❌ Error unsubscribing from notifications:', error);
      throw new Error(error?.message || 'Failed to unsubscribe from notifications');
    }
  };

  // 🔕 Unsubscribe all devices
  const unsubscribeAllDevices = async () => {
    if (!company?.id) {
      throw new Error('Company must be logged in');
    }

    try {
      // Remove all subscriptions from backend
      await pushNotificationService.unsubscribeAllDevices(
        company.id,
        'COMPANY'
      );

      // Also unsubscribe current device from browser
      const registration = await navigator.serviceWorker.ready;
      const subscription = await registration.pushManager.getSubscription();
      if (subscription) {
        await subscription.unsubscribe();
      }

      setIsSubscribedToNotifications(false);

      console.log('✅ Successfully unsubscribed all devices');
      return { success: true, message: 'Successfully unsubscribed all devices' };
    } catch (error) {
      console.error('❌ Error unsubscribing all devices:', error);
      throw new Error(error?.message || 'Failed to unsubscribe all devices');
    }
  };

  // 📋 Get all subscriptions for current company
  const getSubscriptions = async () => {
    if (!company?.id) {
      throw new Error('Company must be logged in');
    }

    try {
      const subscriptions = await pushNotificationService.getSubscriptions(
        company.id,
        'COMPANY'
      );
      return subscriptions;
    } catch (error) {
      console.error('❌ Error fetching subscriptions:', error);
      throw new Error(error?.message || 'Failed to fetch subscriptions');
    }
  };

  // 🔍 Check if current device is subscribed
  const checkSubscriptionStatus = async () => {
    if (!company?.id || !isAuthenticated) return;

    try {
      const registration = await navigator.serviceWorker.ready;
      const subscription = await registration.pushManager.getSubscription();
      
      if (subscription) {
        // Verify with backend
        const subscriptions = await pushNotificationService.getSubscriptions(
          company.id,
          'COMPANY'
        );
        
        const isSubscribed = subscriptions.some(
          (sub) => sub.endpoint === subscription.endpoint
        );
        
        setIsSubscribedToNotifications(isSubscribed);
      } else {
        setIsSubscribedToNotifications(false);
      }
    } catch (error) {
      console.warn('Could not check subscription status:', error);
      setIsSubscribedToNotifications(false);
    }
  };

  // 🔹 Register
  const register = async (data) => {
    try {
      const response = await companyAuthService.registerCompany(data);
      updateAuthState(null, false);
      return response.company;
    } catch (error) {
      throw new Error(error?.message || 'Registration failed');
    }
  };

  // 🔹 Login
  const login = async (credentials) => {
    try {
      const response = await companyAuthService.loginCompany(credentials);
      updateAuthState(response.company, true);
      return response.company;
    } catch (error) {
      throw new Error(error?.message || 'Login failed');
    }
  };

  // 🔹 Logout
  const logout = async () => {
    try {
      await companyAuthService.logoutCompany();
      updateAuthState(null, false);
    } catch (error) {
      updateAuthState(null, false);
      throw new Error(error?.message || 'Logout failed');
    }
  };

  // 🔹 Update profile
  const updateProfile = async (updates, logoFile) => {
    try {
      const updatedCompany = await companyAuthService.editProfile(
        { ...updates, id: company.id },
        logoFile
      );
      updateAuthState(updatedCompany, true);
      return updatedCompany;
    } catch (error) {
      throw new Error(error?.message || 'Failed to update profile');
    }
  };

  // 🔹 Check existing session (auto-login)
  const checkAuthStatus = async () => {
    setIsLoading(true);
    try {
      const companyProfile = await companyAuthService.getProfile();
      if (companyProfile) {
        updateAuthState(companyProfile, true);
      } else {
        updateAuthState(null, false);
      }
    } catch {
      updateAuthState(null, false);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    checkAuthStatus();
  }, []);

  // 🔍 Check subscription status when authenticated
  useEffect(() => {
    if (isAuthenticated && !isLoading && company?.id) {
      checkSubscriptionStatus();
    }
  }, [isAuthenticated, isLoading, company?.id]);

  // 🔔 Auto-subscribe on login (optional)
  useEffect(() => {
    const autoSubscribe = async () => {
      // Only run if authenticated and not already subscribed
      if (!isAuthenticated || isLoading || !company?.id || isSubscribedToNotifications) {
        return;
      }

      // Check if company wants auto-subscribe
      const autoSubscribeEnabled = localStorage.getItem('autoSubscribePushCompany') === 'true';
      
      if (autoSubscribeEnabled) {
        try {
          await subscribeToNotifications('Auto-subscribed device');
        } catch (error) {
          console.warn('Auto-subscribe failed:', error);
        }
      }
    };

    autoSubscribe();
  }, [isAuthenticated, isLoading, company?.id, isSubscribedToNotifications]);

  const value = {
    company,
    login,
    register,
    logout,
    updateProfile,
    subscribeToNotifications,
    unsubscribeFromNotifications,
    unsubscribeAllDevices,
    getSubscriptions,
    isAuthenticated,
    isLoading,
    isSubscribedToNotifications,
  };

  return (
    <CompanyAuthContext.Provider value={value}>
      {children}
    </CompanyAuthContext.Provider>
  );
};

// ✅ Hook for usage
export const useCompanyAuth = () => {
  const context = useContext(CompanyAuthContext);
  if (!context) {
    throw new Error('useCompanyAuth must be used within a CompanyAuthProvider');
  }
  return context;
};