export const menu = [
  { "name": "Special Omelette", "sellingPrice": 3000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Eggs", "Tomato", "Onion", "Green Pepper", "Salt", "Oil"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Rolex Vegetables", "sellingPrice": 3000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Chapati", "Eggs", "Tomato", "Onion", "Cabbage", "Oil"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Rolex Only", "sellingPrice": 2000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Chapati", "Eggs", "Salt", "Oil"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Rolex Chicken with Chips", "sellingPrice": 4000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Chapati", "Eggs", "Chicken", "Salt", "Oil", "Potatoes"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Plain Omelette", "sellingPrice": 1500, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Eggs", "Salt", "Oil"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Vegetables Omelette", "sellingPrice": 2000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Eggs", "Tomato", "Onion", "Green Pepper", "Oil"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Agatogo with Vegetables", "sellingPrice": 3000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Bananas", "Vegetables", "Onion", "Oil", "Salt"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Agatogo with Chicken", "sellingPrice": 6000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Bananas", "Chicken", "Onion", "Oil", "Salt"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Agatogo with Beef & Groundnuts", "sellingPrice": 4000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Bananas", "Beef", "Groundnuts", "Onion", "Salt"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Beef Bouillon", "sellingPrice": 3000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Beef", "Water", "Salt", "Onion", "Spices"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },

  { "name": "Chicken Bouillon", "sellingPrice": 6000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Chicken", "Water", "Onion", "Salt", "Spices"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Fish Bouillon", "sellingPrice": 6000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Fish", "Water", "Salt", "Onion", "Spices"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Spaghetti Bolognaise", "sellingPrice": 6000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Spaghetti", "Minced Meat", "Tomato Sauce", "Onion", "Oil", "Salt"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },

  { "name": "Beef Chips & Rice", "sellingPrice": 4000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Beef", "Rice", "Potatoes", "Oil", "Salt"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Beef & Chips", "sellingPrice": 3500, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Beef", "Potatoes", "Salt", "Oil"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Beef & Fried Potato (Pomme Sautées)", "sellingPrice": 4000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Beef", "Potatoes", "Onion", "Oil", "Salt"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Beef & Boiled Potato", "sellingPrice": 4000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Beef", "Potatoes", "Salt", "Water"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Beef Stew with Rice, Chips & Vegetables", "sellingPrice": 5000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Beef", "Rice", "Potatoes", "Vegetables", "Onion", "Salt"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },

  { "name": "Beef & Banana", "sellingPrice": 3500, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Beef", "Bananas", "Onion", "Salt", "Oil"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Ubugali with Jari/Ragout/Chicken", "sellingPrice": 6000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Maize Flour", "Water", "Salt", "Chicken or Ragout"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Ubugali with Sambaza", "sellingPrice": 5000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Maize Flour", "Water", "Salt", "Sambaza"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Ubugari with Beef", "sellingPrice": 4000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Maize Flour", "Water", "Salt", "Beef"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },

  { "name": "Kaunga with Ragout/Pork/Chicken", "sellingPrice": 6000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Sorghum Paste", "Water", "Salt", "Ragout or Pork or Chicken"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Kaunga with Beef", "sellingPrice": 4000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Sorghum Paste", "Water", "Salt", "Beef"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },

  { "name": "Whole Fish Boiled", "sellingPrice": 20000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Whole Fish", "Water", "Salt", "Onion", "Spices"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Fish Stew with Chips or Rice", "sellingPrice": 6000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Fish", "Tomato Sauce", "Onion", "Salt", "Oil", "Rice or Potatoes"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Fish Fillet with Chips", "sellingPrice": 6000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Fish Fillet", "Oil", "Salt", "Potatoes"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },

  { "name": "Whole Chicken Brian", "sellingPrice": 25000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Chicken", "Spices", "Onion", "Salt"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Half Chicken Brian", "sellingPrice": 15000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Chicken", "Spices", "Onion", "Salt"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Chicken Brian (Plate)", "sellingPrice": 6000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Chicken", "Spices", "Onion", "Salt", "Side Dish"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },

  { "name": "Chicken Reg with Chips or Rice", "sellingPrice": 6000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Chicken", "Salt", "Oil", "Rice or Potatoes"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Chicken Wings with Chips or Rice", "sellingPrice": 6000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Chicken Wings", "Salt", "Oil", "Rice or Potatoes"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },

  { "name": "Beef Brian", "sellingPrice": 5000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Beef", "Spices", "Salt", "Oil"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Igisafuriya (Chicken/Goat)", "sellingPrice": 25000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Chicken or Goat", "Onion", "Tomato", "Spices", "Salt"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Igisafuriya Beef", "sellingPrice": 20000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Beef", "Onion", "Tomato", "Spices", "Salt"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },

  { "name": "Whole Chicken Bouillon", "sellingPrice": 20000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Chicken", "Water", "Salt", "Onion", "Spices"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },

  { "name": "Pork 1kg", "sellingPrice": 8000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Pork", "Salt", "Spices"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Pork 1/2kg", "sellingPrice": 4000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Pork", "Salt", "Spices"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Pork with Chips or Kaunga", "sellingPrice": 6000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Pork", "Salt", "Spices", "Potatoes or Kaunga"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Pork with Banana or Potato", "sellingPrice": 5000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Pork", "Bananas or Potatoes", "Salt", "Oil"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },

  { "name": "Boiled Potato", "sellingPrice": 3000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Potatoes", "Water", "Salt"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Pomme Sautées", "sellingPrice": 3000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Potatoes", "Oil", "Salt", "Onion"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },

  { "name": "Vegetable Soup", "sellingPrice": 3000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Carrots", "Potatoes", "Onion", "Cabbage", "Salt", "Water"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Pumpkin Soup", "sellingPrice": 3000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Pumpkin", "Onion", "Water", "Salt"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Fish Soup", "sellingPrice": 5000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Fish", "Onion", "Tomato", "Salt", "Water"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Chicken Soup", "sellingPrice": 5000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Chicken", "Onion", "Carrots", "Salt", "Water"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },

  { "name": "Mixed Salad", "sellingPrice": 3000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Lettuce", "Tomato", "Onion", "Cucumber"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Chef Salad (Lettuce, Avocado, Eggs)", "sellingPrice": 5000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Lettuce", "Avocado", "Eggs"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Gacumbari", "sellingPrice": 3000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Tomato", "Onion", "Green Pepper"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },

  { "name": "Fish Brochette", "sellingPrice": 2500, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Fish", "Spices", "Salt", "Skewer"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Chicken Brochette", "sellingPrice": 2500, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Chicken", "Spices", "Salt", "Skewer"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Zingaro Brochette", "sellingPrice": 2000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Zingaro Sausage", "Spices", "Skewer"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },

  { "name": "Goat Brochette", "sellingPrice": 1500, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Goat Meat", "Spices", "Salt", "Skewer"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Sausage Brochette", "sellingPrice": 1500, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Sausage", "Skewer"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },

  { "name": "Whole Chicken with Side Dish", "sellingPrice": 15000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Chicken", "Salt", "Spices", "Side Dish"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Half Chicken with Side Dish", "sellingPrice": 10000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Chicken", "Salt", "Spices", "Side Dish"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },

  { "name": "Special Best Corner Chicken", "sellingPrice": 20000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Chicken", "Spices", "Onion", "Side Dish"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Whole Fish with Side Dish", "sellingPrice": 15000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Whole Fish", "Salt", "Spices", "Side Dish"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },

  { "name": "Ikidari", "sellingPrice": 12000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Beef", "Bananas", "Vegetables", "Salt"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" },
  { "name": "Nyama Choma", "sellingPrice": 15000, "purpose": "EATING", "purchasingPrice": null, "difference": null, "discount": 0, "isActive": true, "ingredients": ["Goat Meat", "Salt", "Spices"], "recipe": null, "companyId": "cmisf2on0001zh6q0i1d3i2du" }
]
