/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

declare let self: ServiceWorkerGlobalScope;

// Take control of all pages immediately
clientsClaim();

// Clean up old caches
cleanupOutdatedCaches();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Skip waiting and activate immediately
self.skipWaiting();

// ==========================================
// CACHING STRATEGIES
// ==========================================

// Cache images with CacheFirst strategy
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
    ],
  })
);

// Cache fonts with CacheFirst strategy
registerRoute(
  ({ request }) => request.destination === 'font',
  new CacheFirst({
    cacheName: 'fonts-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 365 * 24 * 60 * 60, // 1 year
      }),
    ],
  })
);

// Cache API calls with NetworkFirst strategy
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 5 * 60, // 5 minutes
      }),
    ],
  })
);

// ==========================================
// PUSH NOTIFICATION HANDLERS
// ==========================================

// 🔔 Handle incoming push notifications
self.addEventListener('push', (event: PushEvent) => {
  console.log('🔔 [Service Worker] Push notification received:', event);
  
  let data: any = {};
  
  // Parse the notification data
  if (event.data) {
    try {
      data = event.data.json();
      console.log('📦 [Service Worker] Notification data:', data);
    } catch (e) {
      console.error('❌ [Service Worker] Failed to parse notification data:', e);
      data = { 
        title: 'Notification', 
        body: event.data.text() || 'You have a new message' 
      };
    }
  } else {
    console.warn('⚠️ [Service Worker] Push event received with no data');
    data = {
      title: 'New Notification',
      body: 'You have a new notification'
    };
  }

  const title = data.title || 'Abytech Hub';
  const options: NotificationOptions = {
    body: data.body || 'You have a new message',
    icon: data.icon || '/pwa-192x192.png',
    badge: data.badge || '/pwa-72x72.png',
    data: data.data || { url: data.url },
    tag: data.tag || 'abytech-notification',
    requireInteraction: data.requireInteraction || false,
    vibrate: data.vibrate || [200, 100, 200],
    silent: false,
    timestamp: Date.now(),
    
  };

  console.warn(options)
  console.warn(options)

  // Add actions if provided
  if (data.actions && Array.isArray(data.actions)) {
    options.actions = data.actions;
  }

  console.log('📢 [Service Worker] Showing notification:', title, options);

  // Show the notification
  event.waitUntil(
    self.registration.showNotification(title, options)
      .then(() => {
        console.log('✅ [Service Worker] Notification displayed successfully');
      })
      .catch((error) => {
        console.error('❌ [Service Worker] Failed to show notification:', error);
      })
  );
});

// 🖱️ Handle notification clicks
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  console.log('🖱️ [Service Worker] Notification clicked:', event);
  
  event.notification.close();


   console.warn('📦 [Service Worker] Passed in Data :', event.notification.data);

  const urlToOpen = event.notification.data?.url || '/';
  const action = event.action;

  console.log('🔗 [Service Worker] Opening URL:', urlToOpen, 'Action:', action);

  event.waitUntil(
    self.clients.matchAll({ 
      type: 'window', 
      includeUncontrolled: true 
    }).then((clientList) => {
      // Check if there's already a window/tab open
      for (const client of clientList) {
        const clientUrl = new URL(client.url);
        const targetUrl = new URL(urlToOpen, self.location.origin);
        
        if (clientUrl.pathname === targetUrl.pathname && 'focus' in client) {
          console.log('✅ [Service Worker] Focusing existing window');
          return client.focus();
        }
      }
      
      // If no matching window found, open a new one
      if (self.clients.openWindow) {
        console.log('🆕 [Service Worker] Opening new window');
        return self.clients.openWindow(urlToOpen);
      }
    }).catch((error) => {
      console.error('❌ [Service Worker] Error handling notification click:', error);
    })
  );
});

// 🚫 Handle notification close
self.addEventListener('notificationclose', (event: NotificationEvent) => {
  console.log('🚫 [Service Worker] Notification closed:', event);
  
  // Optional: Send analytics or track dismissals
  const notificationData = event.notification.data;
  if (notificationData?.trackClose) {
    // You can send analytics here
    console.log('📊 [Service Worker] Tracking notification close');
  }
});

// ==========================================
// BACKGROUND SYNC (Optional)
// ==========================================

self.addEventListener('sync', (event: any) => {
  console.log('🔄 [Service Worker] Background sync:', event.tag);
  
  if (event.tag === 'sync-notifications') {
    event.waitUntil(
      // Perform background sync tasks
      Promise.resolve().then(() => {
        console.log('✅ [Service Worker] Background sync completed');
      })
    );
  }
});

// ==========================================
// SERVICE WORKER LIFECYCLE
// ==========================================

self.addEventListener('install', (event: ExtendableEvent) => {
  console.log('⚙️ [Service Worker] Installing...');
  event.waitUntil(self.skipWaiting());
});

self.addEventListener('activate', (event: ExtendableEvent) => {
  console.log('✅ [Service Worker] Activated');
  event.waitUntil(self.clients.claim());
});

// Handle messages from clients
self.addEventListener('message', (event: ExtendableMessageEvent) => {
  console.log('💬 [Service Worker] Message received:', event.data);
  
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

console.log('🚀 [Service Worker] Initialized with push notification support');