/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

declare let self: ServiceWorkerGlobalScope;

interface ExtendedNotificationOptions extends NotificationOptions {
  vibrate?: number[] | number;
  renotify?: boolean;
  timestamp: any;
  actions?: any;
}

// Take control of all pages immediately
clientsClaim();

// Clean up old caches
cleanupOutdatedCaches();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Skip waiting and activate immediately
self.skipWaiting();

// ==========================================
// BADGE MANAGEMENT
// ==========================================

// Store unread count in IndexedDB for persistence
const DB_NAME = 'NotificationDB';
const STORE_NAME = 'unreadCount';
const UNREAD_KEY = 'count';

async function openDB(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const request = indexedDB.open(DB_NAME, 1);
    
    request.onerror = () => reject(request.error);
    request.onsuccess = () => resolve(request.result);
    
    request.onupgradeneeded = (event: any) => {
      const db = event.target.result;
      if (!db.objectStoreNames.contains(STORE_NAME)) {
        db.createObjectStore(STORE_NAME);
      }
    };
  });
}

async function getUnreadCount(): Promise<number> {
  try {
    const db = await openDB();
    return new Promise((resolve, reject) => {
      const transaction = db.transaction(STORE_NAME, 'readonly');
      const store = transaction.objectStore(STORE_NAME);
      const request = store.get(UNREAD_KEY);
      
      request.onsuccess = () => resolve(request.result || 0);
      request.onerror = () => reject(request.error);
    });
  } catch (error) {
    console.error('❌ [SW Badge] Failed to get unread count:', error);
    return 0;
  }
}

async function setUnreadCount(count: number): Promise<void> {
  try {
    const db = await openDB();
    return new Promise((resolve, reject) => {
      const transaction = db.transaction(STORE_NAME, 'readwrite');
      const store = transaction.objectStore(STORE_NAME);
      const request = store.put(count, UNREAD_KEY);
      
      request.onsuccess = () => resolve();
      request.onerror = () => reject(request.error);
    });
  } catch (error) {
    console.error('❌ [SW Badge] Failed to set unread count:', error);
  }
}

async function incrementUnreadCount(): Promise<number> {
  const current = await getUnreadCount();
  const newCount = current + 1;
  await setUnreadCount(newCount);
  return newCount;
}

async function decrementUnreadCount(): Promise<number> {
  const current = await getUnreadCount();
  const newCount = Math.max(0, current - 1);
  await setUnreadCount(newCount);
  return newCount;
}

async function updateBadge(count: number): Promise<void> {
  console.log(`🔢 [SW Badge] Updating badge to: ${count}`);
  
  try {
    // Update App Badge API (Chrome, Edge, Safari)
    if ('setAppBadge' in self.navigator) {
      if (count > 0) {
        await (self.navigator as any).setAppBadge(count);
        console.log(`✅ [SW Badge] Badge set to ${count}`);
      } else {
        await (self.navigator as any).clearAppBadge();
        console.log('✅ [SW Badge] Badge cleared');
      }
    }
  } catch (error) {
    console.error('❌ [SW Badge] Failed to update badge:', error);
  }
}

// ==========================================
// CACHING STRATEGIES
// ==========================================

// Cache images with CacheFirst strategy
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
    ],
  })
);

// Cache fonts with CacheFirst strategy
registerRoute(
  ({ request }) => request.destination === 'font',
  new CacheFirst({
    cacheName: 'fonts-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 365 * 24 * 60 * 60, // 1 year
      }),
    ],
  })
);

// Cache API calls with NetworkFirst strategy
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 5 * 60, // 5 minutes
      }),
    ],
  })
);

// ==========================================
// PUSH NOTIFICATION HANDLERS
// ==========================================

// 🔔 Handle incoming push notifications
self.addEventListener('push', async (event: PushEvent) => {
  console.log('🔔 [Service Worker] Push notification received:', event);
  
  let data: any = {};
  
  // Parse the notification data
  if (event.data) {
    try {
      data = event.data.json();
      console.log('📦 [Service Worker] Notification data:', data);
    } catch (e) {
      console.error('❌ [Service Worker] Failed to parse notification data:', e);
      data = { 
        title: 'Notification', 
        body: event.data.text() || 'You have a new message' 
      };
    }
  } else {
    console.warn('⚠️ [Service Worker] Push event received with no data');
    data = {
      title: 'New Notification',
      body: 'You have a new notification'
    };
  }

  const title = data.title || 'Abytech Hub';
  const options: ExtendedNotificationOptions = {
    body: data.body || data.message || 'You have a new message',
    icon: data.icon || '/pwa-192x192.png',
    badge: data.icon || data.badge || '/pwa-72x72.png',
    data: data.data || { url: data.url, notificationId: data.notificationId },
    tag: data.tag || data.notificationId || 'abytech-notification',
    requireInteraction: data.requireInteraction || false,
    silent: false,
    vibrate: data.vibrate || [300, 200, 300, 200, 300],
    renotify: true,
    timestamp: Date.now(),
  };

  // Add actions if provided
  if (data.actions && Array.isArray(data.actions)) {
    options.actions = data.actions;
  }

  console.log('📢 [Service Worker] Showing notification:', title, options);

  // Show the notification and update badge
  event.waitUntil(
    (async () => {
      try {
        // Show notification
        await self.registration.showNotification(title, options);
        console.log('✅ [Service Worker] Notification displayed successfully');
        
        // Increment unread count and update badge
        const newCount = await incrementUnreadCount();
        await updateBadge(newCount);
        
      } catch (error) {
        console.error('❌ [Service Worker] Failed to show notification:', error);
      }
    })()
  );
});

// 🖱️ Handle notification clicks
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  console.log('🖱️ [Service Worker] Notification clicked:', event);
  
  event.notification.close();

  console.warn('📦 [Service Worker] Passed in Data:', event.notification.data);

  const urlNotify = event.notification.data?.notificationId 
    ? `${event.notification.data?.url}?notificationId=${event.notification.data?.notificationId}`
    : event.notification.data?.url;

  const urlToOpen = urlNotify || '/';
  const action = event.action;

  console.log('🔗 [Service Worker] Opening URL:', urlToOpen, 'Action:', action);

  event.waitUntil(
    (async () => {
      try {
        // Decrement unread count when notification is clicked
        const newCount = await decrementUnreadCount();
        await updateBadge(newCount);
        
        // Handle window/tab opening
        const clientList = await self.clients.matchAll({ 
          type: 'window', 
          includeUncontrolled: true 
        });
        
        // Check if there's already a window/tab open
        for (const client of clientList) {
          const clientUrl = new URL(client.url);
          const targetUrl = new URL(urlToOpen, self.location.origin);
          
          if (clientUrl.pathname === targetUrl.pathname && 'focus' in client) {
            console.log('✅ [Service Worker] Focusing existing window');
            return client.focus();
          }
        }
        
        // If no matching window found, open a new one
        if (self.clients.openWindow) {
          console.log('🆕 [Service Worker] Opening new window');
          return self.clients.openWindow(urlToOpen);
        }
      } catch (error) {
        console.error('❌ [Service Worker] Error handling notification click:', error);
      }
    })()
  );
});

// 🚫 Handle notification close
self.addEventListener('notificationclose', (event: NotificationEvent) => {
  console.log('🚫 [Service Worker] Notification closed:', event);
  
  // Decrement unread count when notification is dismissed
  event.waitUntil(
    (async () => {
      const newCount = await decrementUnreadCount();
      await updateBadge(newCount);
    })()
  );
  
  // Optional: Send analytics or track dismissals
  const notificationData = event.notification.data;
  if (notificationData?.trackClose) {
    console.log('📊 [Service Worker] Tracking notification close');
  }
});

// ==========================================
// BACKGROUND SYNC (Optional)
// ==========================================

self.addEventListener('sync', (event: any) => {
  console.log('🔄 [Service Worker] Background sync:', event.tag);
  
  if (event.tag === 'sync-notifications') {
    event.waitUntil(
      Promise.resolve().then(() => {
        console.log('✅ [Service Worker] Background sync completed');
      })
    );
  }
});

// ==========================================
// SERVICE WORKER LIFECYCLE
// ==========================================

self.addEventListener('install', (event: ExtendableEvent) => {
  console.log('⚙️ [Service Worker] Installing...');
  event.waitUntil(self.skipWaiting());
});

self.addEventListener('activate', (event: ExtendableEvent) => {
  console.log('✅ [Service Worker] Activated');
  event.waitUntil(
    (async () => {
      await self.clients.claim();
      
      // Initialize badge on activation
      const count = await getUnreadCount();
      await updateBadge(count);
    })()
  );
});

// Handle messages from clients
self.addEventListener('message', (event: ExtendableMessageEvent) => {
  console.log('💬 [Service Worker] Message received:', event.data);
  
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
  
  // Handle badge updates from client
  if (event.data && event.data.type === 'UPDATE_BADGE') {
    event.waitUntil(
      (async () => {
        const count = event.data.count || 0;
        await setUnreadCount(count);
        await updateBadge(count);
      })()
    );
  }
  
  // Handle notification read from client
  if (event.data && event.data.type === 'NOTIFICATION_READ') {
    event.waitUntil(
      (async () => {
        const newCount = await decrementUnreadCount();
        await updateBadge(newCount);
      })()
    );
  }
});

console.log('🚀 [Service Worker] Initialized with push notification and badge support');